# Les formats de sortie {#outputs}

Lors de la création du fichier .Rmd, vous avez dû choisir le format de sortie par défaut du document qui sera généré. Ce choix se retrouve dans l'option `output`de l'en-tête.

Il est possible de modifier le format du document généré, soit en modifiant l'option de l'en-tête ou celle de la fonction knit (via sur la flèche vers le bas du bouton knit ou via les options de la ligne de code).

Il existe deux types de format dans le package `rmarkdown`: documents et présentations. 

Tous les formats possibles sont listés ci-dessous:

  - beamer_presentation
  - context_document
  - github_document
  - html_document
  - html_vignette
  - ioslides_presentation
  - latex_document
  - md_document
  - odt_document
  - pdf_document
  - powerpoint_presentation
  - rtf_document
  - slidy_presentation
  - word_document

Chaque format a son propre lot d'options, qui sont documentées au niveau de la fonction associée (par exemple `?rmarkdown::html_document`).

Comme souvent avec R, il existe de nombreuses extensions qui complètent les possibilités offertes par `{Rmarkdown}`. 
Elles sont listées sur <https://rmarkdown.rstudio.com/formats.html/> et pour les plus connuées d'entre elles présentées dans le [guide Rmarkdown au niveaux des chapitres 5 à 10](https://bookdown.org/yihui/rmarkdown/dashboards.html). 


Lorsqu'on fait appel à un package externe pour définir notre format de sortie, il est nécessaire de le préciser dans l'entête yaml, au niveau de `output:`.
Par exemple, pour utiliser le format 'material' du package `{rmdformats}`, voici ce qu'il faut indiquer :

```{yaml}
---
output: rmdformats::material
---
```


::: {.trucsetastuces}
  **Trucs & Astuces**
  
Attention : quand on inclut du code R dans un document, il faut s'assurer de la compatibilité entre les visualisations produites le(s) format(s) de document(s) choisi(s). 
Généralement, quand on perfectionne une visualisation pour un meilleur affichage au format HTML, on perd la possibilité de produire 
La compatibilité entre types de visualisation et formats de documents doit être vérifiée au cas par cas.  
:::



Nous allons vous présenter les formats les plus utiles.

## html_document

A l'origine, Markdown a été conçu pour générer du HTML, c'est ce format qui a le plus de possibilités parmi tous les formats. 
C'est aussi le plus compatible avec les différents packages R de production de visualisation.

Pour obtenir un document HTML, il faut mettre l'option `output:html_document` dans l'en-tête.

Voici les options utilisées fréquemment:

  - `toc: true` permet d'ajouter une table des matières (table of contents en anglais) à notre document.
  - `toc_depth: 2` permet de définir le niveau de titre le plus bas à mettre dans la table des matières (par défaut 3). 
  - `toc_float : true` permet de rendre la table des matières flottante. 
     Elle sera systématiquement visible, meme si on défile le document. 
     Ce paramètre accepte des options. 
  - `number_sections : true` permet de numéroter les titres. 
  - `theme: flatly` permet de changer le thème du document (tiré de la librairie [Bootswatch](https://bootswatch.com/3/).
  - `fig_width : 7` et  `fig_height : 5` permettent de définir par défaut la largeur et la hauteur des figures.
  - `fig_caption : true` permettent de définir les figures contiennent une légende.


``` {yaml}
---
title: "mon_premier_document"
author: 
  - "Moi"
  - "Toi"
date: "31/10/2022"
output: 
  html_document:
    toc: true
    theme: flatly
---
```


L'ensemble des options est listé page 5 du 
[document de référence Rmarkdown](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

L'un des avantages du format HTML est la possibilité d'appliquer un style personnalisé à l'aide d'un fichier CSS.
Ces documents qui servent à mettre en forme tous les éléments d'une page HTML utilisent une syntaxe spécifique mais extrêmement simple : 
- il faut cibler un élément de la page à partir de sa classe (pour styliser tous les éléments de ce type) ou de son identifiant (pour styliser uniquement cet élément là), on peut assigner une classe spécifique à un élément ;
- il faut spécifier le(s) paramètre(s) qu'on veut styliser (la police, la couleur, l'alignement, l'espacement, etc.) ;
- il faut fixer une valeur pour ce(s) paramètre(s) ;
- les paramètres sont rassemblés entre accolades, séparés de leurs valeurs par un double point, séparés entre eux par un point virgule.
Par exemple, si on veut que tous les titres de niveau H1 soient en gras rouge on écrira :

```{css, eval = F}

h1 {
  font_weight: bold;
  color: red;
}

```

Il est possible d'intégrer directement cette portion de css dans un chunk du document mais la bonne pratique est plutôt de créer un document à part (extension .css ou .scss, c'est une option proposée par Rstudio dans File > New File) et de le référencer dans le yaml, en reprenant l'exemple précédent : 

``` {.md}
title: "mon_premier_document"
author: 
  - "Moi"
  - "Toi"
date: "31/10/2022"
output: 
  html_document:
    toc: true
    theme: flatly
    css: "mon_style.css"
```

À noter : le style fixé par un chunk au sein du document l'emportera sur le style d'un fichier css à part qui l'emportera sur le style fixé par un thème qui l'emportera sur le style de base de l'objet. La dernière information de style lue prévaudra sur les précédentes.

De nombreuses ressources en ligne sont disponibles pour apprendre les bases du css, tous les paramètres qui peuvent être fixés et leurs modalités.

## PDF

Pour générer des documents PDF, il est nécessaire d'avoir installé LaTeX. 
Pour ceux qui ne l'ont pas déjà installé, nous conseillons [TinyTeX](https://yihui.name/tinytex/) qui est une distribution LaTeX légère, portable et facile à maintenir. 
Le package `tinytex` installe automatiquement les packages LaTeX manquants lors que la compilation de documents R Markdown 
en PDF.

Le code suivant permet d'installer `tinytex` :

````{verbatim}
```{r, include=FALSE}
install.packages('tinytex')

install_path <- file.path(Sys.getenv('LOCALAPPDATA'), 'TinyTex', fsep='\\')

tinytex::install_tinytex(dir=install_path)
```
````

LaTeX est un logiciel externe qui vient en complément de R pour produire des PDF. 
Pour pouvoir l'utiliser il faut l'installer (via TinyTeX) mais parfois aussi prévenir R du lieu de ces nouveaux exécutables. 
Pour cela, il faut modifier le fichier de variable d'environnement .Renviron présent dans notre Home.  

Il faut ajouter les lignes de code suivantes :


``` {.md}
TINYTEX_HOME="${LOCALAPPDATA}\TinyTex\bin\win32"
PATH="${TINYTEX_HOME};${PATH}"
```



Il est important de noter qu'en LaTeX, les figures sont flottantes par défaut. 

Même si on crée un graphique dans un bout de code présent sur la 1ere page, celui-ci peut finalement apparaître sur la page suivante. 
LaTeX a tendance à faire apparaitre les figures au début ou à la fin des pages. 
Nous vous 
conseillons de ne traiter le positionnement des figures à la fin, une fois la totalité du contenu écrite. 
Pour cela il faudra utiliser les options de positionnement dans les chunks (par exemple `fig_pos = "h"`)


Pour obtenir un document PDF, il faut mettre l'option `output:pdf_document` dans l'en-tête.

Voici les options utilisées fréquemment:

  - `toc: true` permet d'ajouter une table des matières (table of contents en anglais) à notre document.
  - `toc_depth: 2` permet de définir le niveau de titre le plus bas à mettre dans la table des matières (par défaut 2). 
  - `number_sections : true` permet de numéroter les titres. 
  - `fig_width : 7` et  `fig_height : 5` permettent de définir par défaut la largeur et la hauteur des figures (par défaut 6.5x4.5).
  - `fig_caption : true` permettent de définir les figures contiennent une légende (par défaut `true`).
  
  
  

::::: {.trucsetastuces}::::::    
  **Trucs & Astuces**
Si vous souhaitez accéder à plus d'options de mise en forme de tableau, le  package `kableExtra` contient des fonctions compatibles avec les formats  HMTL et PDF. 
Cependant cela reste compliqué de mettre en forme des tableaux complexes si vous souhaitez plusieurs formats en sortie. 
Nous vous conseillons d'adapter la mise en forme pour chaque format dans deux chunks distincts ou de trouver une nouvelle façon de représenter la donnée.
:::::::::::::::::::::::::::::


::: {.exo}
**Exercice 4**

En repartant du fichier .Rmd de l'exercice précédent :

  - Modifier les options pour avoir un sommaire flottant affichant un seul 
  niveau de titre
  - Changer le thème utilisé
  - Générer le document 
  - Repartir du fichier .Rmd pour générer un document PDF. Il est important 
  de vérifier la compatibilité des éléments définits avec ce nouveau format.
:::
