---
editor_options: 
  markdown: 
    wrap: 72
---

# Pour aller plus loin

## Les documents Quarto

Un document Quarto est un format de document qui permet de combiner du
texte, du code et des visualisations dans un seul fichier, comme un
Rmarkdown en somme. En revanche, Quarto n'est ni dépendant de ni
exclusif à R et Rstudio. Il ne s'agit pas d'un package de R, il faut
l'installer "à part" (mais il est inclus dans l'installation de
Rstudio).

Les différences principales sont :

-   le support multi-langage (R, Python, Javascript, Julia) et
    multi-moteur (Knitr, Jupyter, Observable) ;

-   un rendu amélioré : Quarto offre des options de rendu plus riches et
    plus flexibles, y compris des thèmes et des styles personnalisés
    pour les documents ;

-   l'interactivité : Quarto facilite l'intégration d'éléments
    interactifs, comme des widgets et des visualisations interactives,
    directement dans les documents (à condition de les coder dans leur
    langage d'origine) ;

-   la publication : Quarto propose des options intégrées pour publier
    des documents en tant que sites web, livres électroniques ou
    présentations, avec une configuration minimale ;

-   les fonctionnalités futures : les concepteurs du format ont annoncé
    qu'ils allaient continuer à assurer le support du format Rmd, mais
    que de nouvelles fonctionnalités ne seraient apportées que sur le
    Quarto.

Si vous voulez tester la transition, dans la majorité des cas, un copier
/ coller direct de votre Rmd dans un qmd fonctionnera ! Et pour un test
rapide, créez un nouveau document dans Rstudio en choisissant le format
"Quarto document" proposé et laissez-vous guider.

Vous trouverez toute la documentation, des exemples mais surtout des
guides très complets pour s'autoformer directement [sur le site de
Quarto](https://quarto.org/).

## Affichages sur plusieurs colonnes

cela se fait très bien en format PDF, c'est plus compliqué en HTML. Vous
pourrez avoir besoin de définir un document en plusieurs colonnes, avec
par exemple une illustration sur une moitiée de la page, un texte sur
l'autre.

Pour cela vous aller devoir séparer vos colonnes dans des *"div"*.

Dans rmarkdown, des div commencent par `::: {}` et finissent par `:::`.

Pour ensuite que le document aligne ces blocs l'un à coté de l'autre,
vous devrez utiliser la propriété css `display: flex;` dans une `div`
englobante.

> ASK: est ce que vous pouvez me donner un exemple à ajouter ?
> <https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html> ---
> CCn

## Autres formats de sortie

Il existe des packages permettant d'obtenir des formats de sortie
spécifiques. A chaque fois il convient de vérifier que ces formats des
sorties et votre code sont compatibles.

pagedown pour faire du PDF sans Latex? gouvdown? où on trouve la doc?
distill? les présentations xaringan ? officer et officedown?

## odt_document --\> TODO

les tableaux faits en kableExtra et knitr::kable ne sortent pas
correctement. les graphiques ne sont pas complets (titres coupés par ex)
ce format pourrait etre utile uniquement pour le texte. les graphiques
seraient à faire séparement?

## reference .R files

## Le cache

Si le temps d'éxecution du code est trop long, il est possible
d'utiliser l'option de mise en cache de `knitr` afin d'améliorer les
performances d'éxécution du code.

> ASK: Est ce qu'on parle de cela ou non? --- CCn

## Bibliographie

Voici quelques éléments bibliographiques pour en savoir plus sur R
Markdown mais aussi tous les packages et logiciels en lien avec ce
sujet:

-   [Le guide définitif de
    Rmarkdown](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html)
-   [Le guide de
    référence](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
-   [La syntaxe Markdown sur laquelle s'appuie
    `rmarkdown`]\`(<https://daringfireball.net/projects/markdown/syntax#philosophy>)
-   [Pour en savoir plus sur
    PANDOC](https://pandoc.org/MANUAL.html#pandocs-markdown)
-   [Pour en savoir plus sur TinyTeX](https://yihui.org/tinytex/)
-   [Une vidéo en anglais pour aller plus loin dasn l'utilisation de R
    Markdown](https://www.youtube.com/watch?v=WkF7nqEYF1E)
-   et évidemment les documentations de tous les packages cités!
