# Premières observations

Notre jeu de données contient des informations sur **`r nrow(data_fromage)` fromages**.

On constate tout de suite une grande infamie, **un biais terrible**, [**un crime de lèse fromajesté**]{style="font-size: 2rem;"} :

```{r}
data_FRomage <- data_fromage %>% 
  mutate(origine = if_else(country == "France", "FR", "non FR")) %>% 
  filter(!is.na(origine))
```

```{r, fig.align = 'center'}
library(gouvdown)
library(ggpattern)

ggplot(data_FRomage) +
  geom_bar(aes(x = origine, fill = origine)) +
  geom_bar_pattern(data = data_FRomage[data_FRomage$origine == "FR",],
                   aes(x = origine),
                   pattern = 'image',
                   pattern_filename = 'img/Flag_of_France.svg',
                   fill = 'gold',
                   width = 0.8,
                   height = 0.8) +
  geom_hline(yintercept = 1200, color = 'red') +
  annotate('label', x = 'non FR', y = 1280,
           label = "Nombre de fromages français selon le Centre\n National Interprofessionnel de l'Économie Laitière",
           color = 'red',
           size = 3) +
  scale_fill_manual(values = c("FR" = 'gold', "non FR" = '#AB8763', 'NA' = 'darkgrey'))+
  scale_y_continuous(breaks = seq(0, 1200, 200))+
  labs(title = "Nombre de fromages référencés sur cheese.com par origine") +
  theme_gouv(plot_title_size = 12) +
  theme(legend.position = 'none',
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major.y = element_blank())+
  coord_cartesian(clip = 'off')


```
