---
author: "Guillaume RRRozier"
date: "26/05/2021"
output: html_document
params:
  country_name: "France"
---

```{r setup, include=FALSE, warning = FALSE,message = FALSE,results='hide'}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,message = FALSE)
```

## Vaccination

```{r lib,results='hide'}
library(dplyr)
library(ggplot2)
library(lubridate)
library(COVID19)
data <- covid19()


```

```{r titre, echo = FALSE}
titre <- data %>% 
  filter(administrative_area_level_1 == params$country_name,
         !is.na(people_fully_vaccinated)
         ) %>% 
  filter(date == max(date))
titre_valeur <- format(titre$people_fully_vaccinated, big.mark = " ")
titre_date <- format(titre$date,format = "%A %d %B %Y")
```

---
title: "Rapport Covid 19 - `r titre_valeur` personnes présentant un schéma de vaccination complet au `r titre_date` en `r params$country_name`"
---

```{r viz}
data %>% 
  filter(administrative_area_level_1 == params$country_name,
         lubridate::year(date) > 2020) %>%
  mutate(
    vacnb = as.numeric(people_vaccinated),
    vacnbf = as.numeric(people_fully_vaccinated),
  ) %>% 
  tidyr::pivot_longer(cols=c(vacnb,vacnbf), names_to='type', values_to='nb') %>% 
  ggplot() + 
    geom_line(aes(x = date, y = nb, color=type)) + 
    theme_minimal() + 
    scale_y_continuous(labels = scales::number_format(big.mark = " ")) +
    labs(color='Personnes') +
    scale_color_discrete(labels=c('vaccinées', 'totalement vaccinées')) +
    labs(title = glue::glue("Evolution du nombre de personnes vaccinées contre la COVID-19 en {params$country_name}"), y = NULL)
```


# Pour en savoir plus ...

  - Les variables accessibles dans le modèle de données utilisé sont décrites en ligne dans le [dictionnaire des variables](https://covid19datahub.io/articles/docs.html).
  - Ainsi que la présentation du 'package' [COVID19](https://rviews.rstudio.com/2021/12/08/the-r-package-covid19/)
